---
title: "About Zach Jarou, MD, MBA"
description: |
  Emergency Physician - Data Scientist - Interested in Healthcare Operations, Quality, Informatics, and Policy
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Zach Jarou, MD is an emergency physician and data scientist in Southeast Michigan. He attended medical school at Michigan State University, completed specialty training at the Denver Health Residency in Emergency Medicine, and obtained his MBA from the University of Chicago Booth School of Business while serving as an Administrative Fellow at the University of Chicago Medical Center and completing a Fellowship in Administration, Quality, Informatics, and Policy with the American College of Emergency Physicians. Dr. Jarou is Past President of the Emergency Medicine Residents’ Association, a membership organization of more than 18,000 medical students, residents, fellows, and alumni. His interests include EHR optimization, health information exchange and interoperability, value-based healthcare, operations management, data science, machine learning, and decision modeling.
